- hosts: all
  become: yes
  tasks:

  - name: Copy local files to remote machine
    ansible.builtin.copy:
      src: /home/ubuntu/ansible-homework/Homework4
      dest: ./homework4-copy/
      owner: Tim
      group: devops
      mode: '0755'